# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1581, 771)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.btnCalculateLevel = QtWidgets.QPushButton(self.centralWidget)
        self.btnCalculateLevel.setGeometry(QtCore.QRect(690, 680, 110, 25))
        self.btnCalculateLevel.setObjectName("btnCalculateLevel")
        self.grpAddCycle = QtWidgets.QGroupBox(self.centralWidget)
        self.grpAddCycle.setGeometry(QtCore.QRect(10, 10, 651, 361))
        self.grpAddCycle.setObjectName("grpAddCycle")
        self.btnAddCycle = QtWidgets.QPushButton(self.grpAddCycle)
        self.btnAddCycle.setGeometry(QtCore.QRect(10, 20, 110, 25))
        self.btnAddCycle.setObjectName("btnAddCycle")
        self.tblAddCycle = QtWidgets.QTableWidget(self.grpAddCycle)
        self.tblAddCycle.setEnabled(True)
        self.tblAddCycle.setGeometry(QtCore.QRect(10, 50, 630, 300))
        self.tblAddCycle.setMinimumSize(QtCore.QSize(611, 0))
        self.tblAddCycle.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tblAddCycle.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tblAddCycle.setDragEnabled(True)
        self.tblAddCycle.setDragDropOverwriteMode(True)
        self.tblAddCycle.setAlternatingRowColors(True)
        self.tblAddCycle.setColumnCount(6)
        self.tblAddCycle.setObjectName("tblAddCycle")
        self.tblAddCycle.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblAddCycle.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAddCycle.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAddCycle.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAddCycle.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAddCycle.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAddCycle.setHorizontalHeaderItem(5, item)
        self.grpCycleResults = QtWidgets.QGroupBox(self.centralWidget)
        self.grpCycleResults.setGeometry(QtCore.QRect(10, 380, 651, 331))
        self.grpCycleResults.setObjectName("grpCycleResults")
        self.tblCycleResults = QtWidgets.QTableWidget(self.grpCycleResults)
        self.tblCycleResults.setGeometry(QtCore.QRect(10, 20, 630, 300))
        self.tblCycleResults.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblCycleResults.setColumnCount(5)
        self.tblCycleResults.setObjectName("tblCycleResults")
        self.tblCycleResults.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblCycleResults.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCycleResults.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCycleResults.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCycleResults.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCycleResults.setHorizontalHeaderItem(4, item)
        self.grpTankLevel = QtWidgets.QGroupBox(self.centralWidget)
        self.grpTankLevel.setGeometry(QtCore.QRect(680, 10, 891, 661))
        self.grpTankLevel.setObjectName("grpTankLevel")
        self.grphViewTankLevel = PlotWidget(self.grpTankLevel)
        self.grphViewTankLevel.setGeometry(QtCore.QRect(10, 20, 871, 631))
        self.grphViewTankLevel.setMouseTracking(True)
        self.grphViewTankLevel.setTabletTracking(False)
        self.grphViewTankLevel.setObjectName("grphViewTankLevel")
        self.grpCycleResults.raise_()
        self.grpAddCycle.raise_()
        self.btnCalculateLevel.raise_()
        self.grpTankLevel.raise_()
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1581, 18))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnCalculateLevel.setText(_translate("MainWindow", "Calculate tank level"))
        self.grpAddCycle.setTitle(_translate("MainWindow", "Lists cycles that need to be started"))
        self.btnAddCycle.setText(_translate("MainWindow", "Add cycle"))
        item = self.tblAddCycle.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Component"))
        item = self.tblAddCycle.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Cycle"))
        item = self.tblAddCycle.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Start"))
        item = self.tblAddCycle.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "End"))
        item = self.tblAddCycle.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Optimize"))
        item = self.tblAddCycle.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Remove"))
        self.grpCycleResults.setTitle(_translate("MainWindow", "Results of automatic scheduling"))
        item = self.tblCycleResults.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Component"))
        item = self.tblCycleResults.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Cycle"))
        item = self.tblCycleResults.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Start"))
        item = self.tblCycleResults.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "End"))
        item = self.tblCycleResults.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Status"))
        self.grpTankLevel.setTitle(_translate("MainWindow", "WFI in tank and cycle consumptions"))

from pyqtgraph import PlotWidget
